<?php

namespace Tests\Feature\Api\Post;

use App\Models\Post;
use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class GetPostsTest extends TestCase
{
    use RefreshDatabase;

    private Collection $posts;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::factory()->create();

        $this->posts = Post::factory(5)
            ->for($user, 'author')
            ->create();
    }

    /**
     * A basic feature test example.
     */
    public function test_get_posts(): void
    {
        // sail artisan route:list --path=post
        // sail artisan migrate --database=testing
        // sail artisan test --filter=GetPostsTest

        $response = $this->get(route('post.index'));

        //$response->dd();

        $response->assertOk();

        $response->assertJsonIsArray();

        $response->assertJsonStructure([
            '*' => [
                'author',
                'author_id',
                'company_id',
                'title',
                'content',
                'difficulty',
                'views',
                'read_time',
                'likes',
                'status',
                'comments' => ['*' => []],
                'tags' => ['*' => []],
                'images' => ['*' => []],
            ]
        ]);

    }
}
