<?php

namespace Tests\Feature\Api\Post;

use App\Models\Post;
use App\Models\User;
use Tests\TestCase;

class GetPostTest extends TestCase
{
    private Post $post;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->post = Post::factory()
            ->for(User::factory(), 'author')
            ->create();
    }

    /**
     * A basic feature test example.
     */
    public function test_get_post(): void
    {
        // sail artisan route:list --path=post
        // sail artisan migrate --database=testing
        // sail artisan test --filter=GetPostTest

        $response = $this->get(route('post.show', ['post' => $this->post->id]));

        $response->assertOk();

        //dump($response); это возвращает status и difficulty как Enum и проверка со строкой не проходит.
        //dd($this->post);

        $response->assertJsonStructure([
            'author',
            'author_id',
            'company_id',
            'title',
            'content',
            'difficulty',
            'views',
            'read_time',
            'likes',
            'status',
            'comments' => ['*' => []],
            'tags' => ['*' => []],
            'images' => ['*' => []],
        ]);

        $response->assertJson([
            'author_id' => $this->post->author_id,
            'company_id' => $this->post->company_id,
            'title' => $this->post->title,
            'content' => $this->post->content,
            'difficulty' => $this->post->difficulty,
            'views' => $this->post->views,
            'read_time' => $this->post->read_time,
            'likes' => $this->post->likes,
            'status' => $this->post->status,
        ]);

    }
}
